server.port: 8016

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sfcc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

    username: root
    password: Sifu2020!
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

  redis:
    host: 39.105.160.25 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-wait: 2000ms
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 1000ms

  #rabbitmq:
   # host: 127.0.0.1
   # port: 5672
   # virtual-host: /
   # username: guest
   # password: guest
   # publisher-confirms: true #如果对异步消息需要回调必须设置为true
